
Macro(GENERATE_EICROOT_LIBRARY LIBNAME LINKDEF_FILE)

  INCLUDE_DIRECTORIES( ${INCLUDE_DIRECTORIES} )

  # This is dumb of course; sorry, guys;
  CHANGE_FILE_EXTENSION(*.cxx *.h CXXHEADERS "${CXXSOURCES}")
  SET( HEADERS "${CXXHEADERS}" "${EXTRA_HEADERS}")
  SET( SOURCES "${CXXSOURCES}" "${EXTRA_SOURCES}")

  #if (ROOT5)
  #ROOT_GENERATE_DICTIONARY("${HEADERS}" "${LINKDEF_FILE}" "G__${LIBNAME}.cxx" "${INCLUDE_DIRECTORIES}" )
  #else (ROOT5)
  ROOT_GENERATE_DICTIONARY(G__${LIBNAME} ${HEADERS} LINKDEF ${LINKDEF_FILE})
  #endif (ROOT5)
  SET( SOURCES ${SOURCES} G__${LIBNAME}.cxx )

  ADD_LIBRARY( ${LIBNAME} SHARED ${SOURCES} )

  TARGET_LINK_LIBRARIES( ${LIBNAME} ${ROOT_LIBRARIES} ${DEPENDENCIES})

  INSTALL(TARGETS ${LIBNAME} DESTINATION lib)

  #if (NOT ROOT5)
  INSTALL(FILES ${CMAKE_CURRENT_BINARY_DIR}/lib${LIBNAME}.rootmap ${CMAKE_CURRENT_BINARY_DIR}/lib${LIBNAME}_rdict.pcm DESTINATION lib)
  #endif (ROOT5)

EndMacro(GENERATE_EICROOT_LIBRARY)
